### ISSUE TITLE
CfnPrivateEndpoint  - Error creating vcp Endpoint: MissingEndpoint: 'Endpoint' configuration is required for this service" 

### ISSUE THREAD

**Issue by pahud** [mongodb/awscdk-resources-mongodbatlas#109]
**Describe the bug**

When I create the private endpoint with `CfnPrivateEndpoint`, it returns the error 

```
2:18:08 AM | CREATE_FAILED        | MongoDB::Atlas::PrivateEndpoint    | EndpointEEF1FD8F
Resource handler returned message: "Error creating vcp Endpoint: MissingEndpoint: 'Endpoint' configuration is required for this service" (RequestToken: 29ba9868-d806-8dd3-b458-caccedb2e7eb, HandlerErrorCode: G
eneralServiceException)
```

**To Reproduce**

```ts
new CfnPrivateEndpoint(demoStack, 'Resource', {
  groupId: serverless.project.projectId,
  region: 'US_EAST_1',
  profile: secretProfile,
  privateEndpoints: [
    {
      vpcId: 'vpc-1f5b7e78',
      subnetIds: [
        'subnet-071c85610846aa9c0',
        'subnet-0ef7ac49e1edb06e4',
        'subnet-0e2177a10a166f87d',
      ],
    },
  ],
});
```

**Expected behavior**
The private endpoint should be created.

**Screenshots**

<img width="1475" alt="image" src="https://github.com/mongodb/awscdk-resources-mongodbatlas/assets/278432/c1b88f9e-8c85-4974-a47a-8e2230c474ae">

<img width="1668" alt="image" src="https://github.com/mongodb/awscdk-resources-mongodbatlas/assets/278432/c8dbe073-f791-4395-ac2a-fa77d00a002a">

Looks like the `Atlas Endpoint Service` was created successfully but the cfn handler didn't create the awsvpc endpoint correctly but I am not sure.

--

<br class="Apple-interchange-newline">

**Please complete the following information:**
 - CFN resource version 
 - AWS region where you are running the CFN stack
 us-east-1
 - CDK constructor type and version
`CfnPrivateEndpoint` from awscdk-resources-mongodbatlas 1.0.2
 - Copy of the output of `cdk synth`
 
 ```yaml
 Resources:
  ServerlessInstanceprojectServerlessInstanceFFBB5263:
    Type: MongoDB::Atlas::Project
    Properties:
      Name: project-projectServerlessInstance
      OrgId: 618cb365c835351df903f6ba
      Profile: my-mongo-profile
    Metadata:
      aws:cdk:path: mongodb-demo-stack/ServerlessInstance/projectServerlessInstance/Resource
  ServerlessInstance12909029:
    Type: MongoDB::Atlas::ServerlessInstance
    Properties:
      ContinuousBackupEnabled: true
      Name: my-serverless-instance
      ProjectID:
        Fn::GetAtt:
          - ServerlessInstanceprojectServerlessInstanceFFBB5263
          - Id
      ProviderSettings:
        ProviderName: SERVERLESS
        RegionName: US_EAST_1
      TerminationProtectionEnabled: false
      Profile: my-mongo-profile
    Metadata:
      aws:cdk:path: mongodb-demo-stack/ServerlessInstance/Resource
  Resource:
    Type: MongoDB::Atlas::PrivateEndpoint
    Properties:
      Profile: my-mongo-profile
      GroupId:
        Fn::GetAtt:
          - ServerlessInstanceprojectServerlessInstanceFFBB5263
          - Id
      Region: US_EAST_1
      PrivateEndpoints:
        - VpcId: vpc-1f5b7e78
          SubnetIds:
            - subnet-071c85610846aa9c0
            - subnet-0ef7ac49e1edb06e4
            - subnet-0e2177a10a166f87d
    Metadata:
      aws:cdk:path: mongodb-demo-stack/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/zPSszDQM1BMLC/WTU7J1s3JTNKrDi5JTM7WCUotzi8tSk7VcU7L8y8tKSgtAbFgorU6efkpqXpZxfplhhZ6hmZ6hopZxZmZukWleSWZual6QRAaANHRqw5fAAAA
    Metadata:
      aws:cdk:path: mongodb-demo-stack/CDKMetadata/Default
Outputs:
  ServerlessInstanceConnectionStringB32B56D6:
    Value:
      Fn::GetAtt:
        - ServerlessInstance12909029
        - ConnectionStrings.StandardSrv
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::Contains:
                - - "1"
                  - "2"
                  - "3"
                  - "4"
                  - "5"
                - Ref: BootstrapVersion
        AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.
```     

**Additional context**
