### ISSUE TITLE
 CfnPrivateEndpoint for a dedicated cluster or serverless instance

### ISSUE THREAD

**Issue by pahud** [mongodb/awscdk-resources-mongodbatlas#110]
According to the document, the private endpoint could for a dedicated cluster or a serverless instance.

Looking at `CfnPrivateEndpoint`, it's not clear to me how to control if it's provisioned for a dedicated cluster or a serverless instance.

If I create a PrivateEndpoint like this:

```yaml
  EndpointEEF1FD8F:
    Type: MongoDB::Atlas::PrivateEndpoint
    Properties:
      Profile: my-mongo-profile
      GroupId:
        Fn::GetAtt:
          - ServerlessInstanceprojectServerlessInstanceFFBB5263
          - Id
      Region: us-east-1
      PrivateEndpoints:
        - VpcId: vpc-1f5b7e78
          SubnetIds:
            - subnet-071c85610846aa9c0
            - subnet-0ef7ac49e1edb06e4
            - subnet-0e2177a10a166f87d
```

And check the console, it 's actually a private endpoint for a dedicated cluster.

<img width="550" alt="image" src="https://github.com/mongodb/awscdk-resources-mongodbatlas/assets/278432/c01c765a-ab1e-4241-b906-a35d1736a13d">

Please clarify how to create a private endpoint for a serverless instance instead.

**To Reproduce**
Create the CfnPrivateEndpoint as provided in:

https://github.com/mongodb/awscdk-resources-mongodbatlas/blob/257987ec6132bdffaf929fe8c9a80b7936e3ffd9/examples/l1-resources/private-endpoint.ts#L13-L30

**Expected behavior**
To clarify how to control whether it's for a dedicated cluster or a serverless instance.

**Screenshots**

**Please complete the following information:**
 - CFN resource version 
 - AWS region where you are running the CFN stack
 - CDK constructor type and version
 - Copy of the output of `cdk synth`

**Additional context**
